#!/usr/bin/env bash
# Author: Shivam Sharma

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <clean.tsv>" >&2; exit 1
fi
file="$1"

##############################################################################
# 1. Most popular mechanics (column 13)
awk -F'\t' '
NR>1 && $13!="" {
    n=split($13,a,/ *, */); for(i=1;i<=n;i++) mech[a[i]]++
}
END{
    for(k in mech) if(mech[k]>max){max=mech[k]; name=k}
    printf "The most popular game mechanics is %s found in %d games\n",name,max
}' "$file"

##############################################################################
# 2. Most popular domain (column 14)
awk -F'\t' '
NR>1 && $14!="" {
    n=split($14,a,/ *, */); for(i=1;i<=n;i++) dom[a[i]]++
}
END{
    for(k in dom) if(dom[k]>max){max=dom[k]; name=k}
    printf "The most game domain is %s found in %d games\n",name,max
}' "$file"

##############################################################################
# 3. Pearson r: Year-Published (3) vs Rating (9)
awk -F'\t' '
NR>1 && $3!="" && $9!="" {
    x=$3+0; y=$9+0
    sx+=x; sy+=y; sxx+=x*x; syy+=y*y; sxy+=x*y; n++
}
END{
    r=(n*sxy-sx*sy)/sqrt((n*sxx-sx*sx)*(n*syy-sy*sy))
    printf "The correlation between the year of publication and the average rating is %.3f\n",r
}' "$file"

##############################################################################
# 4. Pearson r: Complexity (11) vs Rating (9)
awk -F'\t' '
NR>1 && $11!="" && $9!="" {
    x=$11+0; y=$9+0
    sx+=x; sy+=y; sxx+=x*x; syy+=y*y; sxy+=x*y; n++
}
END{
    r=(n*sxy-sx*sy)/sqrt((n*sxx-sx*sx)*(n*syy-sy*sy))
    printf "The correlation between the complexity of a game and its average rating is %.3f\n",r
}' "$file"
