#!/usr/bin/env bash


# empty_cells – count the empty cells in every column of the dataset
# Author: Shivam Sharma
# Usage: ./empty_cells <file> <separator>
# Outputs column names and count of empty cells per column.
###############################################################################

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <file> <separator>" >&2
    exit 1
fi

FILE="$1"
SEP="$2"

tr -d '\r' < "$FILE" | awk -v FS="$SEP" '
    NR==1 {
        ncol = NF
        for (i=1; i<=NF; i++) hdr[i] = $i
        next
    }
    {
        for (i=1; i<=ncol; i++)
            if ($i=="") cnt[i]++
    }
    END {
        for (i=1; i<=ncol; i++)
            if (hdr[i] != "")
                printf "%s: %d\n", hdr[i], cnt[i]+0
    }
'
